<form class="validate-ajax form-horizontal row-fluid" action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>" id="<?php echo $this->element->getId(); ?>">
  <?php
  echo $this->element->identifier;
  echo $this->element->csrf;

  $option  = $this->element->getDecorator('ViewScript')->getOptions();
  $id = $option["id"];
  ?>

  <input type="hidden" name="id" value="<?php echo $id ?>">

  <div class="control-group">
    <label class="control-label" for="name">Nom</label>
    <div class="controls">
      <div class="form-group">
        <?php echo $this->element->name ?>
        <?php /* ?><span class="help-inline">Minimum 5 Characters</span><?php */ ?>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="age">Age</label>
    <div class="controls">
      <div class="form-group">
        <?php echo $this->element->age ?>
        <?php /* ?><span class="help-inline">Minimum 5 Characters</span><?php */ ?>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="email">E-mail</label>
    <div class="controls">
      <div class="form-group">
        <?php echo $this->element->email ?>
        <?php /* ?><span class="help-inline">Minimum 5 Characters</span><?php */ ?>
      </div>
    </div>
  </div>

  <?php /* ?>
  <div class="control-group">
    <label class="control-label" for="basicinput">Disabled Input</label>
    <div class="controls">
      <input type="text" id="basicinput" placeholder="You can't type something here..." class="span6" disabled>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Tooltip Input</label>
    <div class="controls">
      <input data-title="A tooltip for the input" type="text" placeholder="Hover to view the tooltip…" data-original-title="" class="span8 tip">
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Prepended Input</label>
    <div class="controls">
      <div class="input-prepend">
        <span class="add-on">#</span><input class="span8" type="text" placeholder="prepend">
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Appended Input</label>
    <div class="controls">
      <div class="input-append">
        <input type="text" placeholder="5.000" class="span8"><span class="add-on">$</span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Dropdown Button</label>
    <div class="controls">
      <div class="dropdown">
        <a class="dropdown-toggle btn" data-toggle="dropdown" href="#">Dropdown Button <i class="icon-caret-down"></i></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <li><a href="#">First Row</a></li>
          <li><a href="#">Second Row</a></li>
          <li><a href="#">Third Row</a></li>
          <li><a href="#">Fourth Row</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Dropdown</label>
    <div class="controls">
      <select tabindex="1" data-placeholder="Select here.." class="span8">
        <option value="">Select here..</option>
        <option value="Category 1">First Row</option>
        <option value="Category 2">Second Row</option>
        <option value="Category 3">Third Row</option>
        <option value="Category 4">Fourth Row</option>
      </select>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Radiobuttons</label>
    <div class="controls">
      <label class="radio">
        <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
        Option one
      </label>
      <label class="radio">
        <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
        Option two
      </label>
      <label class="radio">
        <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">
        Option three
      </label>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Inline Radiobuttons</label>
    <div class="controls">
      <label class="radio inline">
        <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
        Option one
      </label>
      <label class="radio inline">
        <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
        Option two
      </label>
      <label class="radio inline">
        <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">
        Option three
      </label>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Checkboxes</label>
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox" value="">
        Option one
      </label>
      <label class="checkbox">
        <input type="checkbox" value="">
        Option two
      </label>
      <label class="checkbox">
        <input type="checkbox" value="">
        Option three
      </label>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Inline Checkboxes</label>
    <div class="controls">
      <label class="checkbox inline">
        <input type="checkbox" value="">
        Option one
      </label>
      <label class="checkbox inline">
        <input type="checkbox" value="">
        Option two
      </label>
      <label class="checkbox inline">
        <input type="checkbox" value="">
        Option three
      </label>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="basicinput">Textarea</label>
    <div class="controls">
      <textarea class="span8" rows="5"></textarea>
    </div>
  </div>
  <?php */ ?>


  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn" data-spinner-color="#fff" data-style="zoom-in" data-size="xs">
        <?php echo strtoupper($this->translate("Enregistrer")) ?>
      </button>
    </div>
  </div>
</form>