<div class="span9">
    <div class="content">
        <div class="module">
            <div class="module-head">
                <h3>Liste des utilisateurs</h3>
            </div>

            <div class="module-option clearfix">
                <div class="pull-left">
                    <a href="<?php echo $this->baseUrl() ?>/users/modify/do/add" data-resource_type="Category" class="btn btn-primary">Ajouter</a>
                </div>
            </div>

            <div class="module-body table">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped" width="100%" id="data-table">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Age</th>
                            <th>Email</th>
                            <th width="15%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4" class="text-center">Chargement des données ...</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!--/.module-->
    </div>
    <!--/.content-->
</div>
<!--/.span9-->