<div class="span9">
    <div class="content">

        <div class="module">
            <div class="module-head">
                <h3>Utilisateur</h3>
            </div>
            <div class="module-body">

                <?php /* ?>
                <div class="alert">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Warning!</strong> Something fishy here!
                </div>
                <?php */ ?>

                <?php echo $this->form ?>

            </div>
        </div>
    </div>
    <!--/.content-->
</div>
<!--/.span9-->