<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$resource = $request->getControllerName();
$action  = $request->getActionName();

$version = Zend_Registry::get('version');
?>

<!DOCTYPE html>
<!--[if IE 8]><html class="ie ie8"> <![endif]-->
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="<?php echo DEFAULT_LANG_ABBR ?>">
<!--<![endif]-->

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php
  echo $this->headTitle();
  ?>

  <?php
  echo $this->render("statics/header-scripts.phtml");
  echo $this->headLink();
  echo $this->headScript();
  echo $this->render('partial/phpjs.phtml');
  ?>
</head>

<body>
  <?php
  echo $this->render("statics/header.phtml");
  ?>
  <!-- /navbar -->
  <div class="wrapper">
    <div class="container">
      <div class="row">
        <?php
        echo $this->render("statics/sidebar.phtml");
        echo $this->layout()->content;
        echo $this->render("statics/inline-scripts.phtml");
        echo $this->inlineScript();
        ?>
      </div>
    </div>
  </div>

  <?php
  echo $this->render("statics/footer.phtml");
  ?>

</body>

</html>