<link type="text/css" href="<?php echo THEMES_DEFAULT_URL ?>bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link type="text/css" href="<?php echo THEMES_DEFAULT_URL ?>bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
<link type="text/css" href="<?php echo THEMES_DEFAULT_URL ?>css/theme.css" rel="stylesheet">
<link type="text/css" href="<?php echo THEMES_DEFAULT_URL ?>images/icons/css/font-awesome.css" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>

<link type="text/css" rel="stylesheet" href="<?php echo PLUGINS_URL; ?>datatables1.9.4/jquery.dataTables_themeroller.css">

<!-- plugins -->
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>jquery.growl/css/jquery.growl.css" />
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>ladda/css/ladda.min.css" />
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>aos/aos.css" />
<!-- sweet alert -->
<script type='text/javascript' src="<?php echo PLUGINS_URL; ?>swal/sweet_alert.min.js?v=<?php echo $version ?>"></script>

<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom-bootstrap-margin-padding" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/spacing-and-height.css" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom.css?v=<?php echo rand() ?>" type="text/css">