<script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="<?php echo THEMES_DEFAULT_URL; ?>bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- <script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/flot/jquery.flot.js" type="text/javascript"></script> -->
<!-- <script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/flot/jquery.flot.resize.js" type="text/javascript"></script> -->
<!-- <script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/datatables/jquery.dataTables.js" type="text/javascript"></script> -->
<script type='text/javascript' src="<?php echo PLUGINS_URL; ?>datatables1.9.4/jquery.dataTables.min.js?v=<?php echo $version ?>"></script>
<script src="<?php echo THEMES_DEFAULT_URL; ?>scripts/common.js" type="text/javascript"></script>

<!-- plugins -->
<script src="<?php echo PLUGINS_URL ?>autosize.min.js"></script>
<script type='text/javascript' src='<?php echo PLUGINS_URL; ?>jquery.growl/js/jquery.growl.js'></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/spin.min.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/ladda.min.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>aos/aos.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>initial.js"></script>
<!-- sweet alert -->
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/sweetalert.css?v=<?php echo $version ?>">
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/themes/google/google.css?v=<?php echo $version ?>">

<!-- custom -->
<script src="<?php echo THEMES_DEFAULT_URL ?>js/formvalidation.js?v=<?php echo rand() ?>"></script>